import type { Trade, MarketData, Session } from "./types";

export const mockTrades: Trade[] = [
  {
    id: "1",
    pair: "EUR/USD",
    direction: "buy",
    entryPrice: 1.085,
    exitPrice: 1.088,
    pips: 30,
    profit: 300,
    date: "2024-07-29T08:00:00Z",
    session: "London",
    mistakes: ["Late Entry"],
    riskRewardRatio: 2.5,
    notes: "Followed the trend, good exit point.",
    chartUrl: "https://placehold.co/600x400.png",
    lotSize: 1.0,
    stopLoss: 1.083,
  },
  {
    id: "2",
    pair: "GBP/JPY",
    direction: "sell",
    entryPrice: 198.5,
    exitPrice: 198.2,
    pips: 30,
    profit: 250,
    date: "2024-07-29T14:30:00Z",
    session: "New York",
    mistakes: ["Overtrading"],
    riskRewardRatio: 1.5,
    notes: "Forced the trade, should have waited for confirmation.",
    lotSize: 0.5,
    stopLoss: 198.7,
  },
  {
    id: "3",
    pair: "AUD/USD",
    direction: "buy",
    entryPrice: 0.66,
    exitPrice: 0.657,
    pips: -30,
    profit: -150,
    date: "2024-07-28T02:00:00Z",
    session: "Asian",
    mistakes: [],
    riskRewardRatio: 1,
    notes: "News event went against the position.",
    lotSize: 0.5,
    stopLoss: 0.658,
  },
    {
    id: "4",
    pair: "USD/CAD",
    direction: "sell",
    entryPrice: 1.37,
    exitPrice: 1.365,
    pips: 50,
    profit: 500,
    date: "2024-07-28T15:00:00Z",
    session: "New York",
    mistakes: [],
    riskRewardRatio: 3,
    notes: "Perfect setup, textbook trade.",
    chartUrl: "https://placehold.co/600x400.png",
    lotSize: 1.0,
    stopLoss: 1.372,
  },
  {
    id: "5",
    pair: "EUR/USD",
    direction: "sell",
    entryPrice: 1.089,
    exitPrice: 1.09,
    pips: -10,
    profit: -100,
    date: "2024-07-27T09:00:00Z",
    session: "London",
    mistakes: ["FOMO"],
    riskRewardRatio: 0.5,
    notes: "Chased the price and got stopped out.",
    lotSize: 1.0,
    stopLoss: 1.091,
  }
];

export const mockMarketData: MarketData[] = [
  { pair: "EUR/USD", price: 1.0855, change: 0.05, sentiment: "buy", sentimentScore: 65, volatility: "medium" },
  { pair: "GBP/USD", price: 1.2710, change: -0.12, sentiment: "sell", sentimentScore: 30, volatility: "medium" },
  { pair: "USD/JPY", price: 157.80, change: 0.25, sentiment: "buy", sentimentScore: 75, volatility: "high" },
  { pair: "AUD/USD", price: 0.6615, change: 0.10, sentiment: "neutral", sentimentScore: 55, volatility: "low" },
  { pair: "USD/CAD", price: 1.3680, change: -0.08, sentiment: "sell", sentimentScore: 40, volatility: "medium" },
  { pair: "NZD/USD", price: 0.6140, change: 0.03, sentiment: "buy", sentimentScore: 60, volatility: "low" },
  { pair: "EUR/GBP", price: 0.8540, change: 0.15, sentiment: "buy", sentimentScore: 70, volatility: "medium" },
  { pair: "GBP/JPY", price: 198.35, change: -0.30, sentiment: "sell", sentimentScore: 25, volatility: "high" },
];

export const mockSessionData: Record<Session, { pnl: number }> = {
    "Asian": -150,
    "London": 200,
    "New York": 750,
};

export const mistakeTags = ["Overtrading", "Late Entry", "FOMO", "Revenge Trading", "Ignoring SL", "Exiting Too Early"];
